# Define variables

$names = @("Red","Green","Blue","Router")

# Create virtual machine
foreach($name in $names){

Remove-VM -Name $name -Force


}

# SIG # Begin signature block
# MIIFfwYJKoZIhvcNAQcCoIIFcDCCBWwCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUbaO9W5Mv+Ito5sm/SBupXODs
# Rh+gggMUMIIDEDCCAfigAwIBAgIQGgxxhSY8Z7ZFVSS1V899ODANBgkqhkiG9w0B
# AQUFADAgMR4wHAYDVQQDDBVDaGlsbCBWaWJlcyBUZWNoIExhYnMwHhcNMjUwNTMx
# MTUzNTA1WhcNMjYwNTMxMTU1NTA1WjAgMR4wHAYDVQQDDBVDaGlsbCBWaWJlcyBU
# ZWNoIExhYnMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDYmOfM43EX
# ggrVcWcNrEckunO0033WLsJD85AhOUgPltRGsicHBx9ebFVii07oGpAqmIeWPdrs
# 8Kxc+CsIwaXa2Mt6Mm+zcdYgTOee0zSmzXe1L1fFaBlihUK6oob5AZ7GsFU6fgPu
# MBYbtUHrcjyfUTE/4aR2fM0iOHFbDlI+BSecUiVAm7LHkDWh3QwyFzI0uz1FRzaV
# wHIWz5887aVYwNWeLNUToAjMZWWjoOxZ+7FCZ9NpVpVTlsiwbEkrgauSM3ndvhtI
# kGf0uWS4dfk6Q3J2dy9Ygryq1b4TnrGJ+0EGI1UHdS5KMJyrgFKc8sFXdeCsDWj5
# eYEq59U+1n9tAgMBAAGjRjBEMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzAdBgNVHQ4EFgQUyGSkoKHGXemOO/R1Q3xMQkO0HqgwDQYJKoZIhvcN
# AQEFBQADggEBAFvx8k8jXbSe0uSiAPP3waqu418iZhRPPaKTz9Ublt0TT9hYykw5
# LbukUj7beCtkhP+l04TKzTrrmdLjYTAelhX0tLwEDRPCi8GLkjuUkOIyWFHfImOV
# P3hw1hif3j1Bx98sXdsXitDLaQY+P7vUOTWqucvg673e1T12f6h9SW1DS1J5B3Jk
# VUDQOebd5G8/x//V/hlJkjFNEw7QRmD+TS48W41JmznL35zucNPDlSvKrCkItaez
# lmbh6PMlieEwZ84rQBTeZ4cJyBQHsfrmS3cAih93kICvWxgZI/ovwS4b1qTzsXlE
# yEBiUmG/Kdhv4ElaN2xTUMbHlYR3pCybUu0xggHVMIIB0QIBATA0MCAxHjAcBgNV
# BAMMFUNoaWxsIFZpYmVzIFRlY2ggTGFicwIQGgxxhSY8Z7ZFVSS1V899ODAJBgUr
# DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMx
# DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkq
# hkiG9w0BCQQxFgQUTt6wfPVmdhZbZGeFEjUZ2ZOmZScwDQYJKoZIhvcNAQEBBQAE
# ggEAXVZfXJxd8jOPBPQLgyUI2wSvfYiZbIyozh3TKbfLopyim5CzjPk7DZ3shz8J
# r6KkVcFpXFGnkLhwjDoLhX56H1LYtuhi4T/szxCMGhJsFJmGFoBKqdYv8WdIOTzR
# XsZxjGa6GXHqfX83q7l/ue4AEzYn8dtIJlAAwAq6HnCMUMDHYwMWnVPwgd9PoG9j
# mjvThIHr+kwCjAgD/SL8sprf8hwKC/R9+oH9/k+u3tyaB1+MmnKmz6Wocv0xy7Wz
# BVrc/2GepqjB2E4pu7eg3V4NJRKJbdCXn2/qse/j44zXahBvZmi/2LErWTb1vpTE
# 6tK7DjJwh8f+S0n8jYcPTygkKw==
# SIG # End signature block
